### ISSUE TITLE
Shades doesn't seem to work anymore

### ISSUE THREAD

**Issue by damianw** [revan/Shades#1]
I'm not sure how long it's been, but Shades doesn't work on Wikipedia anymore. I would love an update, or some guidance on what might be wrong so that I can submit a PR. 😄

**Comment by revan** [comment]
Seems to be working for me. Does it work on https://en.wikipedia.org/wiki/Muhammad_Ali for you?
The plugin only animates when the underlying CV library is able to identify two eyes in a photo, which unfortunately means it usually skips.

**Comment by damianw** [comment]
Oh, you're right. I think I only looked at Daniel Craig, which is the sample image on the store page. Will close. Thanks!
